"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-28 14:44:19.553565
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "http_cache",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    with op.batch_alter_table("http_cache", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_http_cache_expires_at"), ["expires_at"], unique=False)

    op.create_table(
        "tenants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("actor", sa.String(length=200), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("object_type", sa.String(length=50), nullable=False),
        sa.Column("object_id", sa.String(length=100), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column(
            "meta",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "targets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("root_domain", sa.String(length=253), nullable=False),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("staff_emails", sa.LargeBinary(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("next_scan_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "root_domain"),
    )
    with op.batch_alter_table("targets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_targets_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "authorisation_acks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.LargeBinary(), nullable=False),
        sa.Column("organisation", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=200), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("os_user", sa.String(length=200), nullable=False),
        sa.Column("hostname", sa.String(length=253), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mac", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("authorisation_acks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_authorisation_acks_target_id"), ["target_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_authorisation_acks_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "domain_verifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_result", sa.String(length=200), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "target_id"),
    )
    with op.batch_alter_table("domain_verifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_domain_verifications_target_id"), ["target_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_domain_verifications_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=100), nullable=False),
        sa.Column("module", sa.String(length=64), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("sensitivity", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_scan_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.LargeBinary(), nullable=False),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "target_id", "fingerprint"),
    )
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_findings_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_findings_target_id"), ["target_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_findings_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "scans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("auth_level", sa.String(length=20), nullable=False),
        sa.Column("auth_basis", sa.Text(), nullable=False),
        sa.Column(
            "only_modules",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "skip_modules",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("requested_by", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "tool_versions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scans_status"), ["status"], unique=False)
        batch_op.create_index(
            "ix_scans_target_finished", ["target_id", "finished_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_scans_target_id"), ["target_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_scans_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "finding_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("event", sa.String(length=20), nullable=False),
        sa.Column("kind", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("finding_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_finding_events_scan_id"), ["scan_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_finding_events_target_id"), ["target_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_finding_events_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "module_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("module", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("skip_reason", sa.Text(), nullable=True),
        sa.Column("hint", sa.Text(), nullable=True),
        sa.Column(
            "notes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "stats",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("module_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_module_runs_scan_id"), ["scan_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_module_runs_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "scan_assets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("key", sa.String(length=512), nullable=False),
        sa.Column("source_module", sa.String(length=64), nullable=False),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "facets",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scan_id", "fingerprint"),
    )
    with op.batch_alter_table("scan_assets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scan_assets_scan_id"), ["scan_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_scan_assets_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "scan_findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=100), nullable=False),
        sa.Column("module", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("sensitivity", sa.String(length=20), nullable=False),
        sa.Column("body", sa.LargeBinary(), nullable=False),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scan_id", "fingerprint"),
    )
    with op.batch_alter_table("scan_findings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scan_findings_scan_id"), ["scan_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_scan_findings_tenant_id"), ["tenant_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scan_findings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scan_findings_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_scan_findings_scan_id"))

    op.drop_table("scan_findings")
    with op.batch_alter_table("scan_assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scan_assets_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_scan_assets_scan_id"))

    op.drop_table("scan_assets")
    with op.batch_alter_table("module_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_module_runs_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_module_runs_scan_id"))

    op.drop_table("module_runs")
    with op.batch_alter_table("finding_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_finding_events_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_finding_events_target_id"))
        batch_op.drop_index(batch_op.f("ix_finding_events_scan_id"))

    op.drop_table("finding_events")
    with op.batch_alter_table("scans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scans_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_scans_target_id"))
        batch_op.drop_index("ix_scans_target_finished")
        batch_op.drop_index(batch_op.f("ix_scans_status"))

    op.drop_table("scans")
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_findings_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_findings_target_id"))
        batch_op.drop_index(batch_op.f("ix_findings_status"))

    op.drop_table("findings")
    with op.batch_alter_table("domain_verifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_domain_verifications_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_domain_verifications_target_id"))

    op.drop_table("domain_verifications")
    with op.batch_alter_table("authorisation_acks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_authorisation_acks_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_authorisation_acks_target_id"))

    op.drop_table("authorisation_acks")
    with op.batch_alter_table("targets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_targets_tenant_id"))

    op.drop_table("targets")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_created_at"))
        batch_op.drop_index(batch_op.f("ix_audit_log_action"))

    op.drop_table("audit_log")
    op.drop_table("tenants")
    with op.batch_alter_table("http_cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_http_cache_expires_at"))

    op.drop_table("http_cache")
    # ### end Alembic commands ###
