"""Scan modules. Importing this package registers each one."""

from perimeterwatch.modules import (  # noqa: F401
    breaches,
    bucket_exposure,
    contract_control,
    dependencies,
    dns_resolve,
    dnssec_quality,
    domain_registration,
    email_posture,
    ens_names,
    frontend,
    frontend_pointers,
    github_org,
    github_secrets,
    http_probe,
    jobs_stack,
    lookalikes,
    nameserver_health,
    nuclei_safe,
    origin_exposure,
    packages,
    phishing_lists,
    ports,
    repo_scorecard,
    safe_modules,
    safe_multisig,
    security_contact,
    spf_chain,
    ssh_audit,
    subdomains,
    takeover,
    tls_certs,
    tls_config,
    web_archive,
    zone_transfer,
)
