"""Scan modules. Importing this package registers each one."""

from parapet.modules import (  # noqa: F401
    breaches,
    bucket_exposure,
    contract_control,
    dns_resolve,
    domain_registration,
    email_posture,
    ens_names,
    frontend,
    github_org,
    github_secrets,
    http_probe,
    jobs_stack,
    lookalikes,
    nuclei_safe,
    packages,
    phishing_lists,
    ports,
    repo_scorecard,
    safe_multisig,
    spf_chain,
    ssh_audit,
    subdomains,
    takeover,
    tls_certs,
    tls_config,
    web_archive,
    zone_transfer,
)
